"""Runs the full six-agent diagnostic via the LangGraph orchestrator and
persists every artifact (diagnostics, recommendations, RAGAS scores, deep
eval findings, flow diagrams, executive summary) to SQLite so it survives
process restarts and can be re-fetched by the API.
"""
from __future__ import annotations

from app.agents.orchestrator import run_full_diagnostic
from app.agents.savings_calculator import compute_current_state_baseline
from app.database import crud
from app.database.rehydrate import rehydrate_process_metadata, rehydrate_recommendations
from app.evaluation.kpi_engine import compute_kpis
from app.graphs.mermaid import render_swimlane
from app.schemas.process import ProcessMetadata, ProcessStepDiagnostic, ProcessStepInput
from app.utils.logging import get_logger

logger = get_logger(__name__)


def run_and_persist_pipeline(metadata: ProcessMetadata, raw_steps: list[ProcessStepInput],
                               project_id: int | None = None) -> tuple[int, dict]:
    crud.ensure_db_ready()
    process_id = crud.create_process(project_id, metadata)
    crud.log_audit(process_id, "system", "diagnostic_started", {"steps": len(raw_steps)})

    final_state = run_full_diagnostic(metadata, raw_steps)

    diagnostics = final_state.get("diagnostics", [])
    future_diagnostics = final_state.get("future_diagnostics", [])
    recommendations = final_state.get("recommendations", [])

    # Persist both slices of the structured process map (current + future
    # state), then recommendations - in that order, so recommendations can
    # resolve their process_step_id FK against the just-saved current steps.
    crud.save_diagnostics(process_id, diagnostics, state="current")
    crud.save_diagnostics(process_id, future_diagnostics, state="future")
    crud.save_recommendations(process_id, recommendations)
    crud.save_flow_diagrams(
        process_id, final_state.get("flow_mermaid_current", ""), final_state.get("flow_mermaid_future", "")
    )
    crud.save_executive_summary(
        process_id, final_state.get("executive_summary", ""), final_state.get("savings_summary", {}),
        kpi_summary=final_state.get("kpi_summary", {}),
    )

    for i, note in enumerate(final_state.get("review_notes", [])):
        response_id = crud.save_agent_response(
            process_id, "Reviewer Agent", "review_agent",
            output_text=note.model_dump_json(), round_number=note.round_number,
        )
        if i < len(final_state.get("ragas_scores", [])):
            crud.save_evaluation_score(
                process_id, final_state["ragas_scores"][i], threshold=0.70,
                agent_response_id=response_id, round_number=note.round_number,
            )

    if final_state.get("deep_eval_findings"):
        crud.save_deep_eval_findings(process_id, final_state["deep_eval_findings"])

    crud.log_audit(process_id, "system", "diagnostic_completed", {
        "diagnostics": len(diagnostics), "recommendations": len(recommendations),
    })

    logger.info(f"Persisted diagnostic run for process_id={process_id}")
    return process_id, final_state


def update_current_state_diagnostics(process_id: int, diagnostics: list[ProcessStepDiagnostic]) -> dict:
    """User-initiated correction to the current-state process map (e.g. a
    real owner name instead of "Unknown", a corrected cycle time). Only
    touches deterministic, non-LLM outputs: the persisted step rows, the
    current-state Mermaid diagram, the baseline PCE calc, and the KPI
    benchmark comparison. Recommendations, the executive summary, and the
    future-state flow were generated by LLM calls against the ORIGINAL
    diagnostics and are deliberately left untouched - regenerating them
    would mean re-running the full pipeline, not a lightweight correction.
    """
    data = crud.get_process_full(process_id)
    process = data.get("process")
    if not process:
        raise ValueError(f"Process {process_id} not found")

    metadata = rehydrate_process_metadata(process)
    recommendations = rehydrate_recommendations(data.get("recommendations", []))
    active_recommendations = [r for r in recommendations if not r.is_duplicate]

    crud.save_diagnostics(process_id, diagnostics, state="current")

    current_mermaid = render_swimlane(diagnostics, title=f"{metadata.process_name} - Current State")
    crud.save_flow_diagrams(process_id, current_mermaid, process.flow_mermaid_future or "")

    savings_summary = dict(process.savings_summary_json or {})
    savings_summary["baseline"] = compute_current_state_baseline(metadata, diagnostics)
    kpi_summary = compute_kpis(metadata, diagnostics, active_recommendations, savings_summary)
    crud.save_executive_summary(
        process_id, process.executive_summary or "", savings_summary, kpi_summary=kpi_summary
    )

    crud.log_audit(process_id, "user", "current_state_diagnostics_edited", {"steps": len(diagnostics)})
    logger.info(f"Updated current-state diagnostics for process_id={process_id}")

    return {
        "diagnostics": [d.model_dump() for d in diagnostics],
        "savings_summary": savings_summary,
        "kpi_summary": kpi_summary,
        "flow_mermaid_current": current_mermaid,
    }
